triggers:
- envs: []
  last_enabled_at: 2024-02-05 20:54:53.758407+00:00
  name: green_taxi_etl_schedule
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-02-05 05:00:00
  status: active
  variables:
    bucket_name: <bucketid>
    months: 10,11,12
    project_id: <projectid>
    schema_name: mage
    table_name: green_taxi
    year: 2020
